DROP DATABASE IF EXIST burger_db;
CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers(
	id INT NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR(100) NOT NULL,
	devoured BOOLEAN DEFAULT false NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id)
);

